### ISSUE TITLE
Permission Denied problem

### ISSUE THREAD

**Issue by mozg31337** [Zimbra-Community/ADPassword#1]
Hi

I am trying to setup up the ADPassword to work with my zimbra 8.0 + AD (win2008R2). The users in my AD are located in multiple OUs and not under one ou such as OU=users. I've configured external LDAP authentication in zimbra admin using port 3268 with StartTLS (not over port 636 ssl) and users can successfully authenticate. The reason for using port 3268 and not 389/636 is that i've read that in order to support global searches (as my users are located under multiple OUs) I will need to use port 3268. This seems to have worked as the users can now authenticate, whereas they couldn't when port 389 is used.

I am getting the following error while trying to change the password (as a user or as zimbra admin):

016-04-20 16:23:37,384 INFO  [qtp620860882-453:https://178.248.XXX.XXX:7071/service/admin/soap/SetPasswordRequest] [name=admin@domain.com;mid=1;ip=37.220.XXX.XXX;ua=ZimbraWebClient - GC48 (Linux);] misc - delegated access: doc=SetPassword, authenticated account=admin@domain.com, target account=user@domain.com
2016-04-20 16:23:37,391 INFO  [qtp620860882-453:https://178.248.XXX.XXX:7071/service/admin/soap/SetPasswordRequest] [name=admin@domain.com;mid=1;ip=37.220.XXX.XXX;ua=ZimbraWebClient - GC48 (Linux);] SoapEngine - handler exception
com.zimbra.common.service.ServiceException: permission denied: javax.naming.CommunicationException: simple bind failed: 192.168.XXX.XXX:3268 [Root exception is java.net.SocketException: Connection reset]
ExceptionId:qtp620860882-453:https://178.248.XXX.XXX:7071/service/admin/soap/SetPasswordRequest:1461165817391:2e9ebcde5884fc93
Code:service.PERM_DENIED
        at com.zimbra.common.service.ServiceException.PERM_DENIED(ServiceException.java:288)
        at com.zimbra.adPassword.ADChangePasswordListener.preModify(ADChangePasswordListener.java:45)
        at com.zimbra.cs.account.ldap.ChangePasswordListener.invokePreModify(ChangePasswordListener.java:126)
        at com.zimbra.cs.account.ldap.LdapProvisioning.setPassword(LdapProvisioning.java:5500)
        at com.zimbra.cs.account.ldap.LdapProvisioning.setPassword(LdapProvisioning.java:5242)
        at com.zimbra.cs.service.admin.SetPassword.handle(SetPassword.java:75)
        at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:525)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:388)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:258)
        at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:294)
        at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:210)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at com.zimbra.cs.servlet.ZimbraServlet.service(ZimbraServlet.java:207)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:654)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1320)
        at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:52)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:57)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:82)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:256)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
        at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:45)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
        at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:114)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
        at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:474)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:345)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:316)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:556)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)

at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:317)
        at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:81)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:369)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:944)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1005)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)
2016-04-20 16:23:37,394 INFO  [qtp620860882-453:https://178.248.XXX.XXX:7071/service/admin/soap/SetPasswordRequest] [name=admin@domain.com;mid=1;ip=37.220.XXX.XXX;ua=ZimbraWebClient - GC48 (Linux);] soap - SetPasswordRequest elapsed=10

What could be the problem here?

Andrei

**Comment by ghost** [comment]
Hello Andrei,

Multiple OU's are not supported by this version, but should be by this one:
https://github.com/ronaldomaya/ADPassword

Only I have no experience with that.
