### ISSUE TITLE
Password won't change

### ISSUE THREAD

**Issue by svalavuo** [Zimbra-Community/ADPassword#10]
Zimbra 8.8.12_GA_3794 (Ubuntu 16.04)
FreeIPA, version: 4.6.90.pre1+git20180411 (Ubuntu 18.04)

Major change to provided zmprov -rows are:
zmprov md <domain>.<ext> zimbraAuthLdapBindDn "uid=%u,cn=users,cn=accounts,dc=<domain>,dc=<ext>"

I'm implementing FreeIPA to my system so all account's are not yet there, that's why:
zmprov md <domain>.<ext> zimbraAuthFallbackToLocal TRUE

With those login works fine (with username, not with email).

Password Change doesn't work:
[qtp1258084361-10968:https:https://mail.domain.ext/h/changepass?skin=harmony] [] webclient - permission denied: javax.naming.directory.SchemaViolationException: [LDAP: error code 65 - attribute "unicodepwd" not allowed ]; remaining name 'uid=<user>,cn=users,cn=accounts,dc=<domain>,dc=<ext>'

I'm quite lost with that. :-(

- Samuli

**Comment by ghost** [comment]
Ahh this means that your ldap does not have a unicodepwd attribute OR
the user that is used to changed the password does not have permission to 
change it.

Try using an admin account as bind user and try again.


Alternatively can you see in the documentation of your ldap if it has
unicodepwd. Most LDAP's do. only very old ones (like sun ldap) do not
have it.

If not we need to change it here:
https://github.com/Zimbra-Community/ADPassword/blob/master/src/it/iknowconsulting/adpassword/ADConnection.java#L65

**Comment by svalavuo** [comment]
I'm not quite sure what I did, but now the previous error has gone away.
New ones has appeared though. :-)

`2019-05-28 13:27:51,093 WARN  [qtp1258084361-61684:http://localhost:8080/service/soap/ChangePasswordRequest] [ua=zclient/8.8.12_GA_3803;soapId=21f435dd;] SoapEngine - handler exception
java.lang.NullPointerException
        at java.naming/com.sun.jndi.ldap.AbstractLdapNamingEnumeration.getNextBatch(AbstractLdapNamingEnumeration.java:130)
        at java.naming/com.sun.jndi.ldap.AbstractLdapNamingEnumeration.nextAux(AbstractLdapNamingEnumeration.java:258)
        at java.naming/com.sun.jndi.ldap.AbstractLdapNamingEnumeration.nextImpl(AbstractLdapNamingEnumeration.java:249)
        at java.naming/com.sun.jndi.ldap.AbstractLdapNamingEnumeration.next(AbstractLdapNamingEnumeration.java:203)
        at java.naming/com.sun.jndi.ldap.AbstractLdapNamingEnumeration.next(AbstractLdapNamingEnumeration.java:40)
        at it.iknowconsulting.adpassword.ADConnection.fetchUser(ADConnection.java:96)
        at it.iknowconsulting.adpassword.ADConnection.updatePassword(ADConnection.java:84)
        at it.iknowconsulting.adpassword.ADChangePasswordListener.preModify(ADChangePasswordListener.java:52)
        at com.zimbra.cs.account.ldap.ChangePasswordListener.invokePreModify(ChangePasswordListener.java:128)
        at com.zimbra.cs.account.ldap.LdapProvisioning.setPassword(LdapProvisioning.java:6251)
        at com.zimbra.cs.account.ldap.LdapProvisioning.changePassword(LdapProvisioning.java:5936)
        at com.zimbra.cs.service.account.ChangePassword.handle(ChangePassword.java:95)
        at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:646)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:491)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:278)
        at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:307)
        at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:216)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at com.zimbra.cs.servlet.ZimbraServlet.service(ZimbraServlet.java:211)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
        at com.zimbra.cs.servlet.CsrfFilter.doFilter(CsrfFilter.java:158)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:47)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:116)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ZimbraInvalidLoginFilter.doFilter(ZimbraInvalidLoginFilter.java:117)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:473)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:318)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:288)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:318)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:437)
        at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:84)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.base/java.lang.Thread.run(Thread.java:834)
2019-05-28 13:27:51,094 INFO  [qtp1258084361-61684:http://localhost:8080/service/soap/ChangePasswordRequest] [ua=zclient/8.8.12_GA_3803;soapId=21f435dd;] soap - ChangePasswordRequest elapsed=81
2019-05-28 13:27:51,099 WARN  [qtp1258084361-61685:https:https://mail.<domain>.<ext>/h/changepass?skin=lake] [] webclient - system failure: java.lang.NullPointerException
com.zimbra.common.soap.SoapFaultException: system failure: java.lang.NullPointerException
ExceptionId:qtp1258084361-61684:1559039271093:b6f590dc70841755
Code:service.FAILURE
        at com.zimbra.common.soap.Soap12Protocol.soapFault(Soap12Protocol.java:90)
        at com.zimbra.common.soap.SoapTransport.extractBodyElement(SoapTransport.java:377)
        at com.zimbra.common.soap.SoapTransport.parseSoapResponse(SoapTransport.java:350)
        at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:309)
        at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:193)
        at com.zimbra.common.soap.SoapTransport.invoke(SoapTransport.java:463)
        at com.zimbra.client.ZMailbox.invoke(ZMailbox.java:994)
        at com.zimbra.client.ZMailbox.invoke(ZMailbox.java:979)
        at com.zimbra.client.ZMailbox.invokeJaxbToElement(ZMailbox.java:962)
        at com.zimbra.client.ZMailbox.invokeJaxb(ZMailbox.java:967)
        at com.zimbra.client.ZMailbox.changePassword(ZMailbox.java:828)
        at com.zimbra.client.ZMailbox.changePassword(ZMailbox.java:687)
        at com.zimbra.cs.taglib.tag.ChangePasswordTag.doTag(ChangePasswordTag.java:61)
        at org.apache.jsp.h.changepass._jspx_meth_zm_005fchangePassword_005f0(changepass.java:723)
        at org.apache.jsp.h.changepass._jspx_meth_c_005fcatch_005f0(changepass.java:681)
        at org.apache.jsp.h.changepass.access$12(changepass.java:666)
        at org.apache.jsp.h.changepass$Helper.invoke0(changepass.java:1479)
        at org.apache.jsp.h.changepass$Helper.invoke(changepass.java:1572)
        at org.apache.jsp.tag.web.infra.handleError_tag._jspx_meth_c_005fcatch_005f0(handleError_tag.java:283)
        at org.apache.jsp.tag.web.infra.handleError_tag.doTag(handleError_tag.java:134)
        at org.apache.jsp.h.changepass._jspService(changepass.java:192)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
        at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:107)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
        at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.webClient.filters.RestFilter.doFilter(RestFilter.java:46)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.webClient.filters.ForwardFilter.doFilter(ForwardFilter.java:88)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
        at com.zimbra.webClient.filters.SetHeaderFilter.doFilter(SetHeaderFilter.java:248)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:125)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:473)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:318)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:288)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.webClient.filters.CharEncodingFilter.doFilter(CharEncodingFilter.java:37)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:318)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:437)
        at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:84)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:192)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.base/java.lang.Thread.run(Thread.java:834)
2019-05-28 13:27:51,213 INFO  [qtp1258084361-61672:https:https://localhost:7071/service/admin/soap/GetDomainInfoRequest] [ua=ZCS/8.8.12_GA_3803;soapId=21f435de;] soap - GetDomainInfoRequest elapsed=1
`

I don't really know what to do with those Java -messages (I call them Java vomits). :-)
And I'm quite lost where to seek for the resolution.

- Samuli

**Comment by ghost** [comment]
a null pointer exception in this case it means you omitted to configure something, follow the steps here:
https://github.com/Zimbra-Community/ADPassword#installation-via-the-cli
