### ISSUE TITLE
EHN: allow setting password for Zimbra only users

### ISSUE THREAD

**Issue by maxxer** [Zimbra-Community/ADPassword#16]
When the extension is installed it's impossible to have zimbra only accounts, because it won't allow to set password without an AD user.

When trying to set a password for an email account which doesn't have the corresponding AD user the following exception is returned:

```
2020-01-02 11:46:15,410 WARN  [qtp1708169732-163301:https://zimbra.domain.net:7071/service/admin/soap/SetPasswordRequest] [name=emailonly@domain.net;mid=5;ip=2.1.3.11;port=52473;ua=ZimbraWebClient - FF71 (Win);soapId=6e59aac7;] SoapEngine - handler exception
java.lang.NullPointerException
        at java.naming/com.sun.jndi.ldap.AbstractLdapNamingEnumeration.getNextBatch(AbstractLdapNamingEnumeration.java:130)
        at java.naming/com.sun.jndi.ldap.AbstractLdapNamingEnumeration.nextAux(AbstractLdapNamingEnumeration.java:258)
        at java.naming/com.sun.jndi.ldap.AbstractLdapNamingEnumeration.nextImpl(AbstractLdapNamingEnumeration.java:249)
        at java.naming/com.sun.jndi.ldap.AbstractLdapNamingEnumeration.next(AbstractLdapNamingEnumeration.java:203)
        at java.naming/com.sun.jndi.ldap.AbstractLdapNamingEnumeration.next(AbstractLdapNamingEnumeration.java:40)
        at it.iknowconsulting.adpassword.ADConnection.fetchUser(ADConnection.java:96)
        at it.iknowconsulting.adpassword.ADConnection.updatePassword(ADConnection.java:84)
        at it.iknowconsulting.adpassword.ADChangePasswordListener.preModify(ADChangePasswordListener.java:52)
        at com.zimbra.cs.account.ldap.ChangePasswordListener.invokePreModify(ChangePasswordListener.java:128)
        at com.zimbra.cs.account.ldap.LdapProvisioning.setPassword(LdapProvisioning.java:6265)
        at com.zimbra.cs.account.ldap.LdapProvisioning.setPassword(LdapProvisioning.java:6024)
        at com.zimbra.cs.service.admin.SetPassword.handle(SetPassword.java:103)
        at org.openzal.zal.soap.InternalOverrideDocumentServiceImpl$1.handleRequest(InternalOverrideDocumentServiceImpl.java:72)
        at com.zextras.modules.admin.proxies.AdminProxy.handleRequest(AdminProxy.java:82)
        at org.openzal.zal.soap.InternalDocumentHelper.handle(InternalDocumentHelper.java:75)
        at org.openzal.zal.soap.InternalOverrideAdminDocumentHandler.handle(InternalOverrideAdminDocumentHandler.java:86)
        at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:646)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:491)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:278)
        at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:308)
        at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:217)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at com.zimbra.cs.servlet.ZimbraServlet.service(ZimbraServlet.java:214)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
.....
```

**Comment by ghost** [comment]
Yeah this was not part of the scope of this extension.

I believe the smallest scope for the `change password url` is per domain, so the only solution would be to put your users in a different domain.

You can also change the change password url to a landing page, and redirect your users there based on if they are in AD or not, but that would need some programming know how.

**Comment by maxxer** [comment]
Maybe I didn't explain myself correctly. 

Consider the case where you have a single domain with `zimbraAuthFallbackToLocal` to true, so that you can have email addresses which does not auth against AD. So you create a generic email and try to set a password from the admin console or cli: the above exception is thrown.

IMHO the extension should just catch the exception and allow Zimbra to continue setting the password in its internal db. I see no reason why it should impose all user to be authenticated to the AD database
