### ISSUE TITLE
Problem zimbra and zentyal

### ISSUE THREAD

**Issue by hgeorge123** [Zimbra-Community/ADPassword#4]
Hi I have installed zimbra 8.6 with all patch in ubuntu server 14.04 and I have a zentyal 4.2.2 Segui every step to install the adpassword, but when I try to change the password using the web Interfas zimbra tells me dengado permission checking the log I found this

2016-08-16 21:36:06,944 INFO  [qtp509886383-118:http://127.0.0.1:8080/service/soap/ChangePasswordRequest] [ip=127.0.0.1;ua=zclient/8.6.0_GA_1200;] SoapEngine - handler exception
com.zimbra.common.service.ServiceException: permission denied: javax.naming.CommunicationException: simple bind failed: 10.50.0.13:389 [Root exception is javax.net.ssl.SSLException: java.net.SocketException: Connection reset]
ExceptionId:qtp509886383-118:http://127.0.0.1:8080/service/soap/ChangePasswordRequest:1471397766944:16bd831818376d8d
Code:service.PERM_DENIED
        at com.zimbra.common.service.ServiceException.PERM_DENIED(ServiceException.java:290)
        at it.iknowconsulting.adpassword.ADChangePasswordListener.preModify(ADChangePasswordListener.java:43)
        at com.zimbra.cs.account.ldap.ChangePasswordListener.invokePreModify(ChangePasswordListener.java:128)
        at com.zimbra.cs.account.ldap.LdapProvisioning.setPassword(LdapProvisioning.java:5795)
        at com.zimbra.cs.account.ldap.LdapProvisioning.changePassword(LdapProvisioning.java:5480)
        at com.zimbra.cs.service.account.ChangePassword.handle(ChangePassword.java:95)
        at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:581)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:435)
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:266)
        at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:303)
        at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:213)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at com.zimbra.cs.servlet.ZimbraServlet.service(ZimbraServlet.java:206)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
        at com.zimbra.cs.servlet.CsrfFilter.doFilter(CsrfFilter.java:176)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:351)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:47)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.ZimbraInvalidLoginFilter.doFilter(ZimbraInvalidLoginFilter.java:117)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:457)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:326)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:299)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:544)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
        at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:81)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:462)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:745)
2016-08-16 21:36:06,945 INFO  [qtp509886383-118:http://127.0.0.1:8080/service/soap/ChangePasswordRequest] [ip=127.0.0.1;ua=zclient/8.6.0_GA_1200;] soap - ChangePasswordRequest elapsed=1123
2016-08-16 21:36:06,948 WARN  [qtp509886383-138:https://190.111.120.12:8443/h/changepass?skin=harmony] [] webclient - permission denied: javax.naming.CommunicationException: simple bind failed: 10.50.0.13:389 [Root exception is javax.net.ssl.SSLException: java.net.SocketException: Connection reset]
com.zimbra.common.soap.SoapFaultException: permission denied: javax.naming.CommunicationException: simple bind failed: 10.50.0.13:389 [Root exception is javax.net.ssl.SSLException: java.net.SocketException: Connection reset]
ExceptionId:qtp509886383-118:http://127.0.0.1:8080/service/soap/ChangePasswordRequest:1471397766944:16bd831818376d8d
Code:service.PERM_DENIED
        at com.zimbra.common.soap.Soap12Protocol.soapFault(Soap12Protocol.java:90)
        at com.zimbra.common.soap.SoapTransport.extractBodyElement(SoapTransport.java:355)
        at com.zimbra.common.soap.SoapTransport.parseSoapResponse(SoapTransport.java:328)
        at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:261)
        at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:170)
        at com.zimbra.common.soap.SoapTransport.invoke(SoapTransport.java:408)
        at com.zimbra.client.ZMailbox.invoke(ZMailbox.java:721)
        at com.zimbra.client.ZMailbox.invoke(ZMailbox.java:715)
        at com.zimbra.client.ZMailbox.invokeJaxb(ZMailbox.java:703)
        at com.zimbra.client.ZMailbox.changePassword(ZMailbox.java:598)
        at com.zimbra.client.ZMailbox.changePassword(ZMailbox.java:483)
        at com.zimbra.cs.taglib.tag.ChangePasswordTag.doTag(ChangePasswordTag.java:61)
        at org.apache.jsp.h.changepass._jspx_meth_zm_changePassword_0(org.apache.jsp.h.changepass:611)
        at org.apache.jsp.h.changepass._jspx_meth_c_catch_0(org.apache.jsp.h.changepass:574)
        at org.apache.jsp.h.changepass.access$13(org.apache.jsp.h.changepass:560)
        at org.apache.jsp.h.changepass$changepassHelper.invoke0(org.apache.jsp.h.changepass:1242)
        at org.apache.jsp.h.changepass$changepassHelper.invoke(org.apache.jsp.h.changepass:1321)
        at org.apache.jsp.tag.web.infra.handleError_tag._jspx_meth_c_catch_0(org.apache.jsp.tag.web.infra.handleError_tag:222)
        at org.apache.jsp.tag.web.infra.handleError_tag.doTag(org.apache.jsp.tag.web.infra.handleError_tag:86)
        at org.apache.jsp.h.changepass._jspService(org.apache.jsp.h.changepass:126)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.zimbra.webClient.servlet.JspServlet.service(JspServlet.java:58)
        at org.eclipse.jetty.servlet.JspPropertyGroupServlet.service(JspPropertyGroupServlet.java:139)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
        at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.webClient.filters.RestFilter.doFilter(RestFilter.java:46)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.webClient.filters.ForwardFilter.doFilter(ForwardFilter.java:88)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
        at com.zimbra.webClient.filters.SetHeaderFilter.doFilter(SetHeaderFilter.java:248)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:351)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:116)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:457)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:326)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:299)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.webClient.filters.CharEncodingFilter.doFilter(CharEncodingFilter.java:37)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:544)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
        at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:81)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:462)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ghost** [comment]
Please read and install following:
https://github.com/Zimbra-Community/ADPassword/wiki/Support-for-Zentyal
