### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by M3dS0** [Zimbra-Community/ADPassword#9]
Hello, 
I've configured everything correctly the filters are checked and have no problems but when the user tries to change password gets this error "A network service error has occurred."
and this is the mailbox.log for this error:

[qtp1286783232-19:http://localhost:8080/service/soap/ChangePasswordRequest] SoapEngine - handler exception
java.lang.NullPointerException
	at javax.naming.InitialContext.getURLScheme(InitialContext.java:294)
	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:343)
	at javax.naming.directory.InitialDirContext.getURLOrDefaultInitDirCtx(InitialDirContext.java:106)
	at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:267)
	at it.iknowconsulting.adpassword.ADConnection.fetchUser(ADConnection.java:94)
	at it.iknowconsulting.adpassword.ADConnection.updatePassword(ADConnection.java:84)
	at it.iknowconsulting.adpassword.ADChangePasswordListener.preModify(ADChangePasswordListener.java:52)
	at com.zimbra.cs.account.ldap.ChangePasswordListener.invokePreModify(ChangePasswordListener.java:128)
	at com.zimbra.cs.account.ldap.LdapProvisioning.setPassword(LdapProvisioning.java:6078)
	at com.zimbra.cs.account.ldap.LdapProvisioning.changePassword(LdapProvisioning.java:5763)
	at com.zimbra.cs.service.account.ChangePassword.handle(ChangePassword.java:95)
	at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:607)
	at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:460)
	at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:273)
	at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:303)
	at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:213)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at com.zimbra.cs.servlet.ZimbraServlet.service(ZimbraServlet.java:206)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at com.zimbra.cs.servlet.CsrfFilter.doFilter(CsrfFilter.java:169)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:47)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.ZimbraInvalidLoginFilter.doFilter(ZimbraInvalidLoginFilter.java:117)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:473)
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:318)
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:288)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:318)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:437)
	at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:84)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ghost** [comment]
It looks like you made a typo, as InitialContext.getURLScheme fails, it suggest that the url you provided is not understood by java. 


Try following: https://github.com/Zimbra-Community/ADPassword#installation-via-the-cli

**Comment by M3dS0** [comment]
> It looks like you made a typo, as InitialContext.getURLScheme fails, it suggest that the url you provided is not understood by java. Try following: https://github.com/Zimbra-Community/ADPassword#installation-via-the-cli

Thank you for your reply, I checked everything again but there were no typo problem with my configuration entry.

**Comment by M3dS0** [comment]
> It looks like you made a typo, as InitialContext.getURLScheme fails, it suggest that the url you provided is not understood by java. Try following: https://github.com/Zimbra-Community/ADPassword#installation-via-the-cli

Thank You for your reply, you right, I didn't set zimbraAuthLdapSearchBase .
